-- List the number of films per category.
SELECT 
    c.name AS category,
    COUNT(f.film_id) AS number_of_films
FROM 
    film f
JOIN 
    film_category fc ON f.film_id = fc.film_id
JOIN 
    category c ON fc.category_id = c.category_id
GROUP BY 
    c.name;

-- Retrieve the store ID, city, and country for each store.
SELECT 
    s.store_id,
    c.city,
    co.country
FROM 
    store s
JOIN 
    address a ON s.address_id = a.address_id
JOIN 
    city c ON a.city_id = c.city_id
JOIN 
    country co ON c.country_id = co.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT 
    p.store_id,
    SUM(p.amount) AS total_revenue
FROM 
    payment p
GROUP BY 
    p.store_id;

-- Determine the average running time of films for each category.
SELECT 
    c.name AS category,
    AVG(f.length) AS average_running_time
FROM 
    film f
JOIN 
    film_category fc ON f.film_id = fc.film_id
JOIN 
    category c ON fc.category_id = c.category_id
GROUP BY 
    c.name;

